#!/bin/bash
E_NAME="CUBIC_noname"
RE_DIR="/var/tmp/ln_result"
CODE_DIR="/var/tmp/lena_dev"
SIM_TIME="100"
PEDESTRIAN="1"
lte="lte-ues"
processing="processing"

if [ $# -lt 4 ]; then
	echo "usage rp-..sh <name of backup folder> [<simTime> <isPedestrian> <radio/radio_dev>]"
	exit;
fi

E_NAME=$1
PY_DIR="$REDIR/$4/"

echo "removing old files....."
rm $RE_DIR/$4/*.dat
rm $RE_DIR/$4/*.tmp
rm $RE_DIR/$4/*.raw
rm $RE_DIR/$4/TCP_LOG
rm $RE_DIR/$4/UDP_LOG
rm $RE_DIR/$4/*.txt
rm $RE_DIR/$4/*.svg
rm $RE_DIR/$4/queue
rm $RE_DIR/$4/*.pcap

rm $CODE_DIR/*.pcap
rm $CODE_DIR/DlRxPhyStats.txt
rm $CODE_DIR/DlTxPhyStats.txt
rm $CODE_DIR/UlRxPhyStats.txt
rm $CODE_DIR/DlTxPhyStats.txt
rm $CODE_DIR/lte-ues.out

if [ "$2" != "" ];
	then
		SIM_TIME=$2
		PEDESTRIAN=$3
		echo "t=$SIM_TIME p=$PEDESTRIAN"
fi

echo $E_NAME 
echo $PY_DIR
echo $RE_DIR

BACKUP_FOLDER="$RE_DIR/from_cade/$E_NAME"
echo "backup folder: $BACKUP_FOLDER"

#echo "running $lte nsc UDP ..."
#./waf --run "scratch/$lte --simTime=$SIM_TIME --isTcp=0 --isFading=1 --isPedestrian=$PEDESTRIAN" > $RE_DIR/$4/UDP_LOG 2>&1 
#./waf --run "scratch/$lte --simTime=$SIM_TIME --isTcp=0 --distanceBetweenEnbs=$DISTANCE --isFading=1 --isPedestrian=$PEDESTRIAN" > $RE_DIR/$4/UDP_LOG 2>&1 

echo "running $lte nsc TCP ..."
./waf --run "scratch/$lte --simTime=$SIM_TIME --isTcp=1  --isFading=1 --isPedestrian=$PEDESTRIAN" > $RE_DIR/$4/TCP_LOG 2>&1 
#./waf --run "scratch/$lte" > $RE_DIR/$4/TCP_LOG 2>&1 

cp $CODE_DIR/*.out $RE_DIR/$4/
cp $CODE_DIR/*.pcap $RE_DIR/$4/
cp $CODE_DIR/*.txt $RE_DIR/$4/
cp $CODE_DIR/.dat $RE_DIR/$4/
##copy code
rm -rf $RE_DIR/$4/code
mkdir $RE_DIR/$4/code
cp $CODE_DIR/scratch/$lte.cc $RE_DIR/$4/code
cp $CODE_DIR/src/lte/model/lte-rlc* $RE_DIR/$4/code

cp $CODE_DIR/scratch/$lte.cc $RE_DIR/$4
rm $CODE_DIR/*.pcap
mkdir $BACKUP_FOLDER
cd $RE_DIR
./$processing.sh $E_NAME $4 1
cp -rf $RE_DIR/$4/ $BACKUP_FOLDER 



